### ISSUE TITLE
MassDOT Desired Changes to WZDx v1 Specification

### ISSUE THREAD

**Issue by NeilBoudreau** [usdot-jpo-ode/jpo-wzdx#14]
As mentioned during the meeting held on Monday, August 5th, MassDOT is working of web-based software interface tool to grab work zone data from our Real-Time Smart Work Zone systems and want to be consistent with the WZDx specification.  In a review of the WZDx v1 specification we identified some metrics and device management data elements that we are looking to utilize but have not been incorporated as of yet.  We were hoping that some of these might be considered by FHWA to be part of their WZDx v2 specification or some future version, as this effects our software development schedule.  We are submitting the attached file that provides a breakdown of these items and we are working on more formal specifications for each item that will be submitted in the Pull Requests tab.      [MassDOT requested consideration for spec update_07-30-19.pdf](https://github.com/usdot-jpo-ode/jpo-wzdx/files/3483510/MassDOT.requested.consideration.for.spec.update_07-30-19.pdf)

**Comment by sknick-iastate** [comment]
Neil - There are a lot of good ideas in here but I would recommend looking into the Work Zone Activity Data Framework and Data Dictionary (WZAD) that FHWA has put together ([http://collaboration.fhwa.dot.gov/wzmp/wzdi/Forms/AllItems.aspx]). The WZDx is a way for infrastructure owner and operators (IOOs) such as MassDOT to provide harmonized work zone data to third parties in a public feed and not as an operational tool within the agency (this would be the output of those tools).  From the specification: _"Specifically, the project aims to get data on work zones in to vehicles to help automated driving systems (ADS) and human drivers navigate more safely."_ The FHWA's WZAD is a more encompassing document that covers some of the additional data elements you discuss.

In my opinion, the WZDx is only a single use case (use case 4.2.1 in the WZAD framework) of the 50+ use cases identified in the WZAD framework.  A lot of the data element you identified are likely need for other use cases but may not be needed for a third party public data feed.

Based on some of the suggestions, I think you may be misinterpreting the use of the WZDx.  For example, you suggest including the prime contractor in the metadata.  The WZDx should include all active work zones within the agency and shouldn't be limited to just a single project or contractor.  Looking at some of the existing feed in Iowa and Arizona, they include multiple work zones/projects across multiple contractors.  The WZDx would also not get into the device level details but use these as inputs for the data contents of the WZDx.

Can you also clarify what you mean by static data feed at the bottom of page 1? The WZDx is intended to be a dynamic representation of what exactly is occuring on the roadway which is why those dynamic data elements are included.  The WZDx shouldn't be viewed as a static database but the FHWAs WZAD framework would contain this fairly static data likely in interface 4 or 6.

**Comment by bdelsey64** [comment]
Skylar – Thank you for the clarification. I believe there has been some confusion on our part as to the intended scope of the WZDx specification. This is the first time we are learning that the primary goal of WZDx is to only satisfy the use case of “4.2.1 Work Zone Plan Dissemination to Third-Party Data Providers”. From past discussions, we incorrectly assumed this specification was to eventually facilitate a broader collection of use cases and the corresponding needs of internal stakeholders, especially given the direct participation of some smart work zone vendors to date. However, your comments suggest otherwise, and that any broader scope efforts would be carried out independent of WZDx. 

In our specific case we are looking at standardizing the ingestion of data feeds from smart work zone vendors as well as the publication of data feeds to third-party consumers (i.e. WZDx). Clearly there is a benefit in having the ingested data comprise the necessary data elements required for subsequent dissemination, and thus it makes sense for us to expect smart work zone vendors to also follow the WZDx specification. However, this specification alone is missing a significant amount of information we would need from the smart work zone vendors in order to properly support all other internal needs and use cases. 

MassDOT has an open specification for choosing SWZ vendors, so at any given time, there can be multiple active smart work zone deployments implemented by different vendor system solutions. We need to understand, if and by whom and when, any efforts will be formalized to specify these additional use cases since they appear to fall outside the purview of WZDx. Thank you.

**Comment by sknick-iastate** [comment]
I will let others add in but it is just my opinion that the WZDx aligns with that use case since this is a public facing data feed specification.  

The WZAD framework is intended to be a starting point for the broader scope that would facilitate the use cases both internally and externally that you refer to. The framework currently has 50+ use cases identified.  The WZDx is using the WZAD framework and data dictionary as a reference, as should the other use cases you discuss.

A lot of the items mentioned in the document have been identified in the WZAD framework and data dictionary.  For example, most of the device level details would likely fall under Interface 12 in the WZAD framework but are not currently clearly defined in the data dictionary. The prime contractor would likely fall into Interface 6 in the WZAD framework (in the WZAD Data Dictionary this would be under the Contractor/Sub-contractor data concept).  The performance measures would be in Interface 17 in the WZAD framework and is listed as an external system in the data dictionary.

As you mentioned there is still some information missing/needs further defined  in these documents related to the smart work zone and performance measures since they are referred to as external systems. But the WZAD framework and data dictionary should be the starting point for these use cases.

**Comment by j-d-b** [comment]
Parts of the initial request by Neil have been implemented as part of v2, but this issue is far too broad overall.
