### ISSUE TITLE
specify datum for location coordinates

### ISSUE THREAD

**Issue by sbma44** [usdot-jpo-ode/jpo-wzdx#15]
Although the GPS system's use of EPSG:4326/WGS84 has made it a more-or-less standard choice, there are numerous American authorities that still use NAD83 or even more region-specific datums. This should be specified to avoid ambiguity or imprecisely submitted coordinates. ([context](https://en.wikipedia.org/wiki/Geographic_coordinate_system))

**Comment by DeraldDudley** [comment]
What if we reference the geoJson spec which defines the coordinate reference system you want....


4.  Coordinate Reference System

   The coordinate reference system for all GeoJSON coordinates is a
   geographic coordinate reference system, using the World Geodetic
   System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units
   of decimal degrees.  This is equivalent to the coordinate reference
   system identified by the Open Geospatial Consortium (OGC) URN
   urn:ogc:def:crs:OGC::CRS84.  An OPTIONAL third-position element SHALL
   be the height in meters above or below the WGS 84 reference
   ellipsoid.  In the absence of elevation values, applications
   sensitive to height or depth SHOULD interpret positions as being at
   local ground or sea level.

   Note: the use of alternative coordinate reference systems was
   specified in [GJ2008], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [GJ2008] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.

**Comment by DeraldDudley** [comment]
It also address precision....
https://tools.ietf.org/html/rfc7946#section-3.1.10

3.1.10.  Uncertainty and Precision

   As in [RFC5870], the number of digits of the values in coordinate
   positions MUST NOT be interpreted as an indication to the level of
   uncertainty.

**Comment by sbma44** [comment]
@DeraldDudley I like it. If GeoJSON PRs get merged for affected data fields then I agree that specifying datum is redundant.

**Comment by j-d-b** [comment]
Implemented with GeoJSON in #53
