### ISSUE TITLE
Value of Cross Streets

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#30]
Having a conditional crossStreet value seems odd unless they are assuming it is going to power some in-car Nav that says "construction at Main St. and 3rd Ave". We wouldn't rely on this value and instead would use our own map information to fill in this detail for rider prompts.

**Comment by j-d-b** [comment]
@sghorbanian can you clarify what you're suggesting here?

Note as a consumer you're free to use this information as desired. The purpose of the cross street fields (`beginning_cross_street` `ending_cross_street` as optional is so that data producers can include cross street information if available.

**Comment by j-d-b** [comment]
Closed for lack off of clarity in the issue and discussion. @sghorbanian, feel free to comment if you have further questions.
