### ISSUE TITLE
Add Road informations to the EndLocation Data Frame

### ISSUE THREAD

**Issue by MarcLabb** [usdot-jpo-ode/jpo-wzdx#52]
Issue name: Add Road informations to the EndLocation Data Frame
 ## Summary
I propose to add road informations such as RoadName, Number and Direction to the EndLocation Data Frame.

 ## Motivation
Because a common  workzone could begin on a highway and ending on another road or highway, I think that this informations should be important to provide as well. 
It is not clear that all the workzone is on the same road all along.

**Comment by j-d-b** [comment]
As of v2 the concept of a "data frame" no longer exists, but the idea behind this issue is still relevant. That is, the spec defines `road_name`, `road_number`, and `direct` on the `road_event` entity, but there is no way to specify if a road event starts and ends on a different roadway, and no clarification if those fields should represent the start or end roadway information.

**Comment by lynnerandolph** [comment]
TxDOT has this information as part of a lane closure or work zone. There is a start location consisting of a lat/lon, roadway, direction, cross street and the end location has that same information.

**Comment by j-d-b** [comment]
See #78, which suggests creating a new road event if the roadway changes.

**Comment by j-d-b** [comment]
Closed in favor of #78.
