### ISSUE TITLE
type_name in Type Of Work table optional

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/jpo-wzdx#74]
Issue name: “[Clarification / New feature / Question] — Summarize topic”
 ## Summary
Based on the discussion during v2 development, I thought that the `type_name` in the [types_of_work table](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/master/feed-content/data-tables/types_of_work.md) was going to be optional.  

Looking back at the [original pull request](https://github.com/usdot-jpo-ode/jpo-wzdx/pull/33) before it was modified for the relational data model the comments refer to this being optional as well.

In Iowa I don't think we currently have the ability to provide the level of detail without making a lot of assumptions. 

 ## Proposed changes
Change `type_name` to optional

**Comment by j-d-b** [comment]
I just read through the original pull request and don't see where `type_name` was intended to be optional. In the original changes as well before it was modified, this field is required ([see here](https://github.com/usdot-jpo-ode/jpo-wzdx/blob/457c44db78f0e5da82fa55c241933974d9980b0f/full-spec/full-spec.md)).

I understand that some DOTs don't have the ability to provide the work type information, and that's fine, as the `types_of_work` field on the feed output (corresponding to the types of work table) is optional. There is no requirement to include any type of work information on the road event. 

The only case where making `type_name` optional would have an impact is if a producer wants to supply `is_architectural_change` but can't give the `type_name`. In this case making `type_name` conditional (required if `is_architectural_change` is not specified) rather than optional makes more sense as both fields on the table should not be able to be optional as then there would be no reason to even include an entry. Is wanting to specify the `is_architectural_change` without giving the `type_name` the scenario you're talking about at Iowa?

**Comment by sknick-iastate** [comment]
I see now the statement "For every record in the road_event table there exists zero or more records in the types_of_work table" which makes it optional.  I was looking at the table and thinking it was required to give a `type_name` for every work zone.  I agree with your need to have this required.
