### ISSUE TITLE
Include Detour Information for a Road Event

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#82]
*This issue is a replacement of the older PR #34, which was pre-v2 and not properly discussed in an issue prior to the PR creation.*

Several subgroup members have expressed interest in adding detour information to the `road_event` entity.

The original PR was based on MassDOT's use case, which is a human-readable text description of detour information, if available. This would be accomplished simply by adding an optional text field to the road event entity called `detour_information`. Producers and consumers use this as they wish.

Others suggested having a linestring geometry for the detour and/or other mapping/machine-focused detour information would be helpful.

This issue is intended to be used to discuss what consumers would like to get out of the detour information and thus inform what should be added to the spec.

**Comment by Mahsa-Ettefagh** [comment]
Comments received during the [V3 Specification Update Subgroup](https://github.com/usdot-jpo-ode/jpo-wzdx/wiki/WZDx-v3-Specification-Update-Subgroup-Meeting-Notes,-2020-04-29) meeting on 4/29/2020: 

- Neil Boudreau, MassDOT: A map based tool to show the detour is certainly the way to go.
- Lynne Randolph: Right now, we do not typically include detour information, so no real comments on that
- Neil Boudreau, MassDOT: The need will be here eventually so we might as well go for it now.
- Jim Williams (INRIX): What would the underlying standard be for the linestring? Or will that be discussed in the pull? 
- Chris Brookes MDOT: the thing to also keep in mind is you have two types of detours as we have truck detours and passanger car detours at times.
- Paula okunieff (ICF): The geometry will need to be lane level geometry and the accuracy need to be at very accurate level
- Lynne Randolph: should include a textual description as well
- Jim Williams (INRIX): Looking forward to participating on the #82 PR. Not sure I can be a point person on that item. Not sure I can be a point person on #82 but looking forward to participating on the PR.

**Comment by DeraldDudley** [comment]
Proposed Options to Address Detours

1.	Do nothing
This option does not resolve the need to inform drivers/AVs about available detours which would divert traffic from Work Zones.

2.	Add a detour_information field to the road_event table to hold a human-readable text description of detour information.
This option addresses the need to describe detours but does not provide the geometry and lane modeling which could be used by drivers and AVs to navigate around detours.

3.	Add a road_event_type field to the road_event tables to distinguish work zones from detours.
This option extends the data model to accommodate detours and leverages the existing geometry, description field, and lane models to describe and map detours.

4.	Create a new model to describe detours.
This option creates a new and separate model to describe and map detours.  It does not leverage the existing work zone data model.

**Comment by sknick-iastate** [comment]
Is it possible to add another table for detours then have an additional detour geometry?  I'm not sure whether this is acceptable but it seems like a simple solution.  So it would be an addition table in the ERD that would have the following fields plus some additional that may also be necessary.

`detour_id`
`road_event_id`
`detour_geometry_type`
`detour_geometry`

**Comment by Dunge** [comment]
I weight in in favor of adding (optional) detour information along with geometry, I believe it's an important part of workzone works and could help traffic system to inform drivers more efficiently.

As for creating a new table or re-using road_event. Let's see what exist in road_event:

- The name itself is still good (a detour IS a road event, even if it's not a workzone)
- Geometry we want to keep
- Road name / number / direction / cross street are still possible to be filled in. Milepost would depend on the road type.
- Start/end date could also be filled. Most of the time the detour would be the same as the main workzone, but sometimes they might change over time.
- Lanes descriptions can also be filled, but might be less important since they won't likely to be changed compared normal operation.
- Vehicle impact / worker present / reduced speed limit / restrictions. Those are the fields that might not be relevant to detours. Is it worth to create a second similar table to remove these fields? They are mostly all optional, so I don't think they are polluting.

So personally for now I would vote to go with option 3 and re-use the table with a different type. But it might become problematic at long term if we add more and more field exclusive to workzones.

Also, to address Chris Brookes comment, it would currently be impossible to specify if it's a detour for cars or trucks. I guess an additional field could be set up for this, which could weight in the choice of having a different table.

**Comment by DeraldDudley** [comment]
Looks like option 3 above is preferred.  Which is easily implemented by inserting a type field into the road_events table.  The road_event types will have an enumeration including work_zone and detour. 

**Geojson detour example:** https://gist.github.com/DeraldDudley/d5a1d9e5a6dd3add5f7a1b9d007a5c2c

**Updated road_events table below**

Field Name | Data Type | Description | Conformance | Notes
-- | -- | -- | -- | --
road_event_id | ID | A   unique identifier issued by the data feed provider to identify the work zone   project or activity | Required | Primary   Key
feed_info_id | ID | Identifies   the feed to which a road event is related. | Required | Foreign   Key to road_event_feed_info
**type** | **Enumeration;   Text** | **Indicates the type of road event** | **Required** | **Enumeration:   “work_zone”, “detour”**
subidentifier | ID | A   unique identifier issued by data feed provider that provides additional   references to project or activity | Optional | This   identifier may be used in more than one feed as a reference to an   agency project number or permit ID
geometry_type | Enumeration:   Multipoint or LineString | May   be represented as a linestring or a multipoint as defined in the GeoJson   specification. | Required |  
geometry | Coordinate(s);   Float | A   coordinate pair or an array of coordinates. In either case, the first   coordinate is the beginning point and the last coordinate is the ending point   of the road event | Required | Coordinate   pairs and coordinate arrays are formatted according to the geoJson spec
road_name | Text | Publicly   known name of the road on which the event occurs. | Required |  
road_number | Text | The   road number designated by a jurisdiction such as a county, state or   interstate | Optional | Examples   I-5, VT 133
direction | Enumeration;   Text | The   digitization direction of the road that is impacted by the event. This value   is based on the standard naming for US roadways and indicates the direction   the traffic flow regardless of the real heading angle. | Required | Example northbound (for   I-5 North); See Direction   Enumerated Type
beginning_cross_street | Text | Name   or number of the nearest cross street along the roadway where the event   begins | Optional |  
ending_cross_street | Text | Name   or number of the nearest cross street along the roadway where the event ends | Optional |  
beginning_milepost | Float | The   linear distance measured against a milepost marker along a roadway where the   event begins | Optional | A   milepost or mile marker is a surveyed distance posted along a roadway   measuring the length (in miles or tenth of a mile) from the south west to the   north east. These markers are typically notated on State and local government   digital road networks. Provide link to description of milepost method in   metadata file.
ending_milepost | Float | The   linear distance measured against a milepost marker along a roadway where the   event ends | Optional | A   milepost or mile marker is a surveyed distance posted along a roadway   measuring the length (in miles or tenth of a mile) from the south west to the   north east. These markers are typically notated on State and local government   digital road networks. Provide link to description of milepost method in   metadata file.
beginning_accuracy | Enum:   Estimated or Verified | Indicates   how the beginning coordinate was defined. | Required | see Spatial   Verification Enumerated Type
ending_accuracy | Enum:   Estimated or Verified | Indicates   how the ending coordinate was defined. | Required | see Spatial   Verification Enumerated Type
start_date | DateTime | The   UTC time and date when the event begins. | Required | All   date/time formats shall use ISO 8601 Data elements and interchange formats –   Information interchange. Example: 2016-11-03T19:37:00Z
end_date | DateTime | The   UTC time and date when the event ends. | Required | All   date/time formats shall use ISO 8601 Data elements and interchange formats –   Information interchange. Example: 2016-11-03T19:37:00Z
start_date_accuracy | Enum:   Estimated or Verified | A   measure of how accurate the start Date Time is. | Required | see Time   Verification Enumerated Type
end_date_accuracy | Enumeration:   Estimated or Verified | A   measure of how accurate the end Date Time is. | Required | see Time   Verification Enumerated Type
event_status | Enumeration;   Text | The   status of the event | Optional | See Event   Status Enumerated Type
total_num_lanes | Integer | The   total number of lanes associated with the road segment designated by the   event geometry | Optional | A   segment is a part of a roadway in a single direction designated the event   geometry
vehicle_impact | Enumeration;   Text | The   impact to vehicular lanes along a single road in a single direction | Required | See Vehicle   Impact Enumerated Type
workers_present | Boolean | A   flag indicating that there are workers present in the event space | Optional |  
reduced_speed_limit | Integer | The   reduced speed limit posted within the event space | Optional |  
restrictions | Enumumeration;   Text | Zero   or more road restrictions applying to the work zone road segment associated   with the work zone delimited by semicolons | Optional | These   are included as flags rather than detailed restrictions. Detailed   restrictions are coded to specific lanes in the lane_restrictions table.   See Road   Restriction Enumerated Type
description | Text | Short   free text description of work zone | Optional | This   will be populated with formal phrases in a later WZDx version
issuing_organization | Text | The   organization issuing the data feed | Optional | Will   create a list in a   future version
creation_date | DateTime | The   UTC time and date when the activity or event was created | Optional | All   date/time formats shall use ISO 8601 Data elements and interchange formats –   Information interchange. Example: 2016-11-03T19:37:00Z
update_date | DateTime | The   UTC time and date when the activity or event was updated | Optional | All   date/time formats shall use ISO 8601 Data elements and interchange formats –   Information interchange. Example: 2016-11-03T19:37:00Z

**New Enumeration table**
Work Zone Event Type

Enumeration

Type | Description
-- | --
work_zone | An   area of a trafficway with highway construction, maintenance, or utility-work   activities. A work zone is typically marked by signs, channeling devices,   barriers, pavement markings, and/or work vehicles. It extends from the first   warning sign or flashing lights on a vehicle to the "End of Road   Work" sign or the last traffic control device. A work zone may be for   short or long durations and may include stationary or moving activities.   Inclusions:       Long-term        stationary highway construction such as building a new bridge, adding        travel lanes to the roadway,1 and extending an existing        trafficway.2    Mobile        highway maintenance such as striping the roadway, median, and roadside        grass mowing/landscaping, and pothole repair.    Short-term        stationary utility work such as repairing electric, gas, or water lines        within the trafficway.      Exclusions:       Private        construction, maintenance, or utility work outside the trafficway.      1 The AASHTO term equivalent   to roadway is traveled way.   2 The AASHTO term equivalent   to trafficway is highway, street, or road.       Source:   https://www.fhwa.dot.gov/publications/publicroads/99mayjun/workzone.cfm
detour | A temporary rerouting of road users onto an existing trafficway to   avoid a work zone or other impedance.       Source: https://mutcd.fhwa.dot.gov/htm/2009/part6/part6c.htm

**Used By**
The Event type enumeration is used by the following fields

Field Name | Data Table
-- | --
Type | road_events

**Comment by j-d-b** [comment]
@DeraldDudley thanks for the proposed solution. Some comments below.

> Looks like option 3 above is preferred. Which is easily implemented by inserting a type field into the road_events table. The road_event types will have an enumeration including work_zone and detour.

I think what may be missing is a clear way to link a detour to a specific work zone. Right now the `subidentifier` property on the road event can be used to link road events together in some way. This is being used differently by differently DOTs right now and there aren't specific rules required for using it. Possibly the `subidentifier` on a detour could be the work zone event road event ID it's related to, but then one couldn't link a detour to multiple work zone road events. Alternatively the detour could be given the same `subidentifier` as all the work zone road events to group everything in a work zone area, but then it wouldn't be possible to specify a detour is only for a single work zone road event, which is necessary as there may be a different detour for different roadway directions, etc.

> **Geojson detour example:** https://gist.github.com/DeraldDudley/d5a1d9e5a6dd3add5f7a1b9d007a5c2c

This example doesn't clearly link the detour to the road events or the road events to each other as the subidentifier is not used for the work zones and it's not clear what it means for the detour. 

> **type** 	**Enumeration; Text** 	**Indicates the type of road event** 	**Required** 	**Enumeration: “work_zone”, “detour”**

To follow the dash-delineated naming standard we've used for every other enum, this should be `work-zone`, and `detour`.

> subidentifier 	ID 	A unique identifier issued by data feed provider that provides additional references to project or activity 	Optional 	This identifier may be used in more than one feed as a reference to an agency project number or permit ID

We may need to add another property like this or clarify potential usage in this description.

**Comment by DeraldDudley** [comment]
> @DeraldDudley thanks for the proposed solution. Some comments below.
> 
> > Looks like option 3 above is preferred. Which is easily implemented by inserting a type field into the road_events table. The road_event types will have an enumeration including work_zone and detour.
> 
> I think what may be missing is a clear way to link a detour to a specific work zone. Right now the `subidentifier` property on the road event can be used to link road events together in some way. This is being used differently by differently DOTs right now and there aren't specific rules required for using it. Possibly the `subidentifier` on a detour could be the work zone event road event ID it's related to, but then one couldn't link a detour to multiple work zone road events. Alternatively the detour could be given the same `subidentifier` as all the work zone road events to group everything in a work zone area, but then it wouldn't be possible to specify a detour is only for a single work zone road event, which is necessary as there may be a different detour for different roadway directions, etc.

I agree this is a problem. I suggest creating a new issue to make object relationships explicit.  A possible solution is adopting the JSCalendar **[Relation](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-27#section-1.4.10)** object.  It's explicit and is much more flexible than the current subidentifier property.

### From JSCalendar ###
A Relation object defines the relation to other objects, using a possibly empty set of relation types. The object that defines this relation is the linking object, while the other object is the linked object. 
 The Relation object has the following properties:

- @type: "String" (mandatory)
Specifies the type of this object.  This MUST be "Relation".

- relation: "String[Boolean]" (optional, default: empty Object)
Describes how the linked object is related to the linking object.  The relation is defined as a set of relation types.  If empty, the relationship between the two objects is unspecified.

Keys in the set MUST be one of the following values, or specified in the property definition where the Relation object is used, or a value registered in the IANA JSCalendar Enum Registry, or a vendor-specific value:

- "first": The linked object is the first in a series the linking object is part of.

 - "next": The linked object is the next in a series the linking object is part of.

 - "child": The linked object is a subpart of the linking object.

 - "parent": The linking object is a subpart of the linked object.

The value for each key in the set MUST be true.

### End JSCalendar ###

If I'm reading the JSCalendar spec right, implementations would look like this...
 - "relation": {"parent": "MC85-WB-75-79"}
 - Meaning the feature/road event is a child of the referenced "road_event_id": "MC85-WB-75-79"

It is possible to create and array of relation objects
 - "relation": [{"child": "MC85-WB-75-79"},{"child": "MC85-WB-75-80"}, {"child": "MC85-WB-75-81"}]
 - But its easier to maintain child objects which reference parent objects

> 
> > **Geojson detour example:** https://gist.github.com/DeraldDudley/d5a1d9e5a6dd3add5f7a1b9d007a5c2c
> 
> This example doesn't clearly link the detour to the road events or the road events to each other as the subidentifier is not used for the work zones and it's not clear what it means for the detour.
> 
Agreed.  I'll correct and repost.

> > **type** 	**Enumeration; Text** 	**Indicates the type of road event** 	**Required** 	**Enumeration: “work_zone”, “detour”**
> 
> To follow the dash-delineated naming standard we've used for every other enum, this should be `work-zone`, and `detour`.
> 
Agreed.  I'll correct and repost.

> > subidentifier ID A unique identifier issued by data feed provider that provides additional references to project or activity Optional This identifier may be used in more than one feed as a reference to an agency project number or permit ID
> 
> We may need to add another property like this or clarify potential usage in this description.

Please see  my comment above about using the [Relation](https://tools.ietf.org/html/draft-ietf-calext-jscalendar-27#section-1.4.10) object from JSCalendar.

> Lastly, though this the effect this change has on the feed structure is minor, I'm curious how this will be implemented in the data models. Are you thinking there will be separate data tables for each road event type?

I think we need to adopt a class/object model that aligns with the adoption of the geoJSON spec.  As it is now we have different modeling techniques in the spec.  The E-R design was a good start getting the data organized but, as this spec grows, an object model will make modeling easier.  I'll put together an object model to show the update sub group.  If approved we can start a new issue.

In an ER Diagram there would be one Road_Events table into which a type field is inserted.  In an object model, work-zone and detour would be types of road event.  In either model the implementation would be the same with only the road_event.type values being different.

**Comment by DeraldDudley** [comment]
Version 2 of the Geojson detour example; Clearer use of the road_event.subidentifier field to relate detours to work-zones.
https://gist.github.com/DeraldDudley/d5a1d9e5a6dd3add5f7a1b9d007a5c2c 

Version 2 of the updated road_events table; Uses the correct naming convention for the type enumeration of work-zone and detour; not work_zone and detour.

Field Name | Data Type | Description | Conformance | Notes
-- | -- | -- | -- | --
road_event_id | ID | A unique identifier issued by the data feed   provider to identify the work zone project or activity | Required | Primary Key
feed_info_id | ID | Identifies the feed to which a road event is   related. | Required | Foreign Key to road_event_feed_info
type | Enumeration; Text | Indicates the type of road event | Required | Enumeration: “work-zone”, “detour”
subidentifier | ID | A unique identifier issued by data feed   provider that provides additional references to project or activity | Optional | This identifier may be used in more than one   feed as a reference to an agency project number or permit ID
geometry_type | Enumeration: Multipoint or LineString | May be represented as a linestring or a   multipoint as defined in the GeoJson specification. | Required |  
geometry | Coordinate(s); Float | A coordinate pair or an array of   coordinates. In either case, the first coordinate is the beginning point and   the last coordinate is the ending point of the road event | Required | Coordinate pairs and coordinate arrays are   formatted according to the geoJson spec
road_name | Text | Publicly known name of the road on which the   event occurs. | Required |  
road_number | Text | The road number designated by a jurisdiction   such as a county, state or interstate | Optional | Examples I-5, VT 133
direction | Enumeration; Text | The digitization direction of the road that   is impacted by the event. This value is based on the standard naming for US   roadways and indicates the direction the traffic flow regardless of the real   heading angle. | Required | Example northbound (for I-5   North); See Direction Enumerated Type
beginning_cross_street | Text | Name or number of the nearest cross street   along the roadway where the event begins | Optional |  
ending_cross_street | Text | Name or number of the nearest cross street   along the roadway where the event ends | Optional |  
beginning_milepost | Float | The linear distance measured against a   milepost marker along a roadway where the event begins | Optional | A milepost or mile marker is a surveyed   distance posted along a roadway measuring the length (in miles or tenth of a   mile) from the south west to the north east. These markers are typically   notated on State and local government digital road networks. Provide link to   description of milepost method in metadata file.
ending_milepost | Float | The linear distance measured against a   milepost marker along a roadway where the event ends | Optional | A milepost or mile marker is a surveyed   distance posted along a roadway measuring the length (in miles or tenth of a   mile) from the south west to the north east. These markers are typically   notated on State and local government digital road networks. Provide link to   description of milepost method in metadata file.
beginning_accuracy | Enum: Estimated or Verified | Indicates how the beginning coordinate was   defined. | Required | see Spatial Verification Enumerated   Type
ending_accuracy | Enum: Estimated or Verified | Indicates how the ending coordinate was   defined. | Required | see Spatial Verification Enumerated   Type
start_date | DateTime | The UTC time and date when the event begins. | Required | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange.   Example: 2016-11-03T19:37:00Z
end_date | DateTime | The UTC time and date when the event ends. | Required | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange.   Example: 2016-11-03T19:37:00Z
start_date_accuracy | Enum: Estimated or Verified | A measure of how accurate the start Date   Time is. | Required | see Time Verification Enumerated Type
end_date_accuracy | Enumeration: Estimated or Verified | A measure of how accurate the end Date Time   is. | Required | see Time Verification Enumerated Type
event_status | Enumeration; Text | The status of the event | Optional | See Event Status Enumerated Type
total_num_lanes | Integer | The total number of lanes associated with   the road segment designated by the event geometry | Optional | A segment is a part of a roadway in a single   direction designated the event geometry
vehicle_impact | Enumeration; Text | The impact to vehicular lanes along a single   road in a single direction | Required | See Vehicle Impact Enumerated Type
workers_present | Boolean | A flag indicating that there are workers   present in the event space | Optional |  
reduced_speed_limit | Integer | The reduced speed limit posted within the   event space | Optional |  
restrictions | Enumumeration; Text | Zero or more road restrictions applying to   the work zone road segment associated with the work zone delimited by   semicolons | Optional | These are included as flags rather than   detailed restrictions. Detailed restrictions are coded to specific lanes in   the lane_restrictions table. See Road Restriction Enumerated Type
description | Text | Short free text description of work zone | Optional | This will be populated with formal phrases   in a later WZDx version
issuing_organization | Text | The organization issuing the data feed | Optional | Will create a list in a future version
creation_date | DateTime | The UTC time and date when the activity or   event was created | Optional | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange.   Example: 2016-11-03T19:37:00Z
update_date | DateTime | The UTC time and date when the activity or   event was updated | Optional | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange.   Example: 2016-11-03T19:37:00Z

Version 2 of the Enumeration Table; Uses the correct naming convention for the type enumeration of work-zone and detour; not work_zone and detour.

Work Zone Event Type
Enumeration

Type | Description
-- | --
work-zone | An area of a trafficway with highway   construction, maintenance, or utility-work activities. A work zone is   typically marked by signs, channeling devices, barriers, pavement markings,   and/or work vehicles. It extends from the first warning sign or flashing   lights on a vehicle to the "End of Road Work" sign or the last   traffic control device. A work zone may be for short or long durations and   may include stationary or moving activities. Inclusions: Long-term stationary   highway construction such as building a new bridge, adding travel lanes to   the roadway,1 and extending an existing trafficway.2 Mobile highway   maintenance such as striping the roadway, median, and roadside grass   mowing/landscaping, and pothole repair. Short-term stationary utility work   such as repairing electric, gas, or water lines within the trafficway.   Exclusions: Private construction, maintenance, or utility work outside the   trafficway. 1 The AASHTO term equivalent to roadway is traveled way. 2 The   AASHTO term equivalent to trafficway is highway, street, or road.            Source: https://www.fhwa.dot.gov/publications/publicroads/99mayjun/workzone.cfm
detour | A temporary rerouting of road users onto an   existing trafficway to avoid a work zone or other impedance.            Source: https://mutcd.fhwa.dot.gov/htm/2009/part6/part6c.htm

Used By
The Event type enumeration is used by the following fields

Field Name | Data Table
-- | --
Type | road_events

**Comment by DeraldDudley** [comment]
ER Diagram adding the road_events.type field to accommodate work-zones and detours. 
https://github.com/DeraldDudley/wzd_geoJson/blob/master/road_event_erd_v3_detour.jpg

**Comment by Polly-Okunieff** [comment]
Couple of comments: 
1. "type" attribute can need to be extended to "truck detour", "sidewalk detour", etc. 
2. We may want to establish business rule for how we overload the subidentifier field.  The detour record subidentifier points to the WZ road event id, and the WZ has a flag that indicates that there is one or more detour records.

**Comment by j-d-b** [comment]
Added in #119
