### ISSUE TITLE
Standardize lane numbering start side

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#98]
This issue was spawned during discussion about solutions for #66.

There appears to be great interest removing the ability for a producer to choose the side (`left` or `right`) from which lane number counting begins and instead standardizing the side as part of the WZDx specification.

#66 was more specifically resolved in #97, intended for the v3.0 release, without standardizing the counting start side. Thus this issue is intended to be a place to continue the discussion regarding standardizing the start side.

I know @davidcraig4300 has some thoughts on this.

**Comment by CraigMoore-Sea** [comment]
Open Street Map (OSM) uses left to right as the standard for identifying lanes; which would align with WZDx using left side to begin lane numbering.

**Comment by eli104** [comment]
Designating the innermost (left-most ) travel lane as Lane 1, with numbering going upward to the outside lane can also found in the AASHTO NTIMC document, "Traffic Incident Response - Lane Designation Terminology" [http://ntimc.transportation.org/Pages/NTIMCPublicationsandProducts.aspx](url). 
The document notes: 
- When using lane numbers, the far left lane shall be called “Lane 1”. Each lane to the right is numbered sequentially 2 through n. 
- Shoulders should be identified using “right/left” and/or “inside/outside” and the term “shoulder”; The left shoulder is the inside shoulder and the right shoulder is the outside shoulder.  i.e. inside (or left) shoulder,

**Comment by lynnerandolph** [comment]
It does get murky when you have odd lane configurations though. We have some where there's a shoulder for both the HOV lane and the normal lane so "right/outside" shoulder would have more than one.

Lynne

**Comment by eli104** [comment]
Agree... I-91 in Connecticut has an empty lane (no barriers) between the left travel lane and the HOV lane. It is signed occasionally as "Crossing divider prohibited," but is often used as a breakdown lane for travelers using the HOV (since there is no shoulder or breakdown lane to use if you get a flat in the HOV lane).

**Comment by jewel1965** [comment]
To keep the lane numbering flexible for various roadway configurations and travel directions, I feel that it is better to allow data producers to define which side of the roadway the lane numbering begins. 

The lane_edge_reference can be a feed level element when the data producer deals with single roadway and travel direction configuration, or an event level element when dealing with multiple roadway configuration. If the lane_edge_reference is included in both feed and event levels, the event level lane_edge_reference will get priority over the feed level lane_edge_reference.

**Comment by davidcraig4300** [comment]
Mapping companies tend to use the left road edge as the reference side.  Thereby making the left most lane, lane #1 (this would include the shoulder if there is one on the left side).   

I personally do NOT like leaving this as an optional direction.  I can see potential issues with using the data, if lane #1 flips from left side of the road to right side of the road from record to record.  I believe we should pick a side and standardize on it.  

My vote would be for the left side.

**Comment by lynnerandolph** [comment]
For C2C, we number from median outward, which is like starting on the left, so I'd vote left. We typically include shoulders in numbering though, so we should make it clear whether we want shoulders or not. We have some pretty complex roadway configurations.

[cid:image001.png@01D6552B.05A4A800]
[cid:image002.png@01D6552B.05A4A800]
[cid:image003.png@01D6552B.43C95130]

Lynne

**Comment by CraigMoore-Sea** [comment]
I agree there are benefits to standardizing the lane edge reference and left seems to be most common. It is a simple transformation for producers to transpose their data if they are using right edge.

A numbering standard that incorporates all lanes types is preferable. In urban areas many roads have something other than a shoulder or travel lane as their first lane; such as a bike lane, HOV lane, or parking lane. The idea of using the first 'improved surface' lane seems most flexible. Having a discussion about what 'improved surface' means to various IOOs would be helpful. In Seattle and many urban areas 'improved surface' means paved.

**Comment by RHolt-RIDOT** [comment]
I agree standardized lane reference is way to go, for the various reasons already noted.  Would any party prefer to have a different scheme to worry about just because some boundary on a map is being crossed?  As others have noted, Traffic Incident Management (TIM)/AASHTO groups in the U.S. have already (a while back now) recommended 'Left to Right' and so to me it makes sense to work off of that - WITH ONE EXCEPTION - I recommend referring to right/left (and NOT inside/outside) RE: shoulders, because at least to me the former is more intuitive as long as specifications are clear that the user is looking forward in the direction of traffic.   Example image shown below is from a R.I. TIM manual, FYI.

For the several folks that have already noted the unique and/or non-standardized lane types and configurations - **THANK YOU FOR NOTING THESE!**, they are and will remain a reality in the field, with 'special use' lanes expected in many areas to proliferate in coming years.  If my wish comes true these specifications will eventually be able to be comprehensive enough to standardize on how to code/cover all such cases of closed surface travel ways, whatever they may be (e.g., not only marked HOV, Bus, Bicyclist, etc. lanes, but also pedestrian sidewalks, etc. - i'll post a separate discussion RE: this soon).  I'm not a code writer, but for lynnerandolph's noted cases of "more than one" I sure hope there's a way for the Specification to accommodate such, and it's just a matter of coming up with a convention (unless someone thinks or has found it easier to differentiate any facilities that are separated by barrier/bollard/similar?).    

Also CraigMoore-Sea RE: 
> The idea of using the first 'improved surface' lane seems most flexible. Having a discussion about what 'improved surface' means to various IOOs would be helpful. In Seattle and many urban areas 'improved surface' means paved.

While i think many at RIDOT would interpret 'First improved surface' to mean "first paved surface", to me that term still seems a little more vague than ideal, since a gravel shoulder on the right side of an undivided 2-lane roadway without any edge line markings could certainly be interpreted as improved (if not for the environment, but for the safety of road users).  I'm all for being flexible but only if the Specification is as clear as it can be RE: intent/definition of the terms used.

![image](https://user-images.githubusercontent.com/68556160/87961521-cc940280-ca83-11ea-98fa-b956b6141fd5.png)

**Comment by j-d-b** [comment]
Added in #94
